"""empty message

Revision ID: 1afd5871e532
Revises: aa4fdd615c5e
Create Date: 2022-07-12 11:22:24.463557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afd5871e532'
down_revision = 'aa4fdd615c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
