"""empty message

Revision ID: 56457f96dbb2
Revises: 1afd5871e532
Create Date: 2022-07-12 11:38:00.293924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56457f96dbb2'
down_revision = '1afd5871e532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
